name: Build APK from ZIP

on:
  workflow_dispatch:
    inputs:
      zipUrl:
        description: 'URL ZIP project'
        required: true
      jobId:
        description: 'Unique job ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install base deps
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl git openjdk-17-jdk

      - name: Install Flutter
        run: |
          FLUTTER_VERSION="3.41.0-stable"
          curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}.tar.xz -o flutter.tar.xz
          tar xf flutter.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version

      - name: Download ZIP
        run: |
          mkdir build
          curl -L "${{ inputs.zipUrl }}" -o build/project.zip
          unzip -q build/project.zip -d build/project

      - name: Detect Project Type
        run: |
          ROOT=$(find build/project -name pubspec.yaml | head -n 1)

          if [ ! -z "$ROOT" ]; then
            echo "TYPE=flutter" >> $GITHUB_ENV
            echo "DIR=$(dirname $ROOT)" >> $GITHUB_ENV
            echo "Detected Flutter project"
            exit 0
          fi

          ROOT=$(find build/project -name gradlew | head -n 1)

          if [ ! -z "$ROOT" ]; then
            echo "TYPE=gradle" >> $GITHUB_ENV
            echo "DIR=$(dirname $ROOT)" >> $GITHUB_ENV
            echo "Detected Gradle project"
            exit 0
          fi

          echo "Project type not supported"
          exit 1

      - name: Build Flutter APK
        if: env.TYPE == 'flutter'
        run: |
          cd "$DIR"
          flutter pub get
          flutter build apk --release

      - name: Build Gradle APK
        if: env.TYPE == 'gradle'
        run: |
          cd "$DIR"
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Collect APK
        run: |
          mkdir result
          APK=$(find build -name "*release*.apk" | head -n 1)

          if [ -z "$APK" ]; then
            echo "APK not found"
            exit 1
          fi

          cp "$APK" result/app_${{ inputs.jobId }}.apk
          cd result
          zip app_${{ inputs.jobId }}.zip app_${{ inputs.jobId }}.apk

      - name: Push APK
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://github.com/Joodev65/Joomodss.id.git repo
          mkdir -p repo/X
          cp result/app_${{ inputs.jobId }}.zip repo/X/

          cd repo
          git config user.name "Actions Bot"
          git config user.email "actions@github.com"

          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/Joodev65/Joomodss.id.git
          git add .
          git commit -m "Build APK ${{ inputs.jobId }}" || true
          git push
